version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
